name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build release
        run: npm run build

  tag:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release Tag
        uses: actions/github-script@0.10.0
        with:
          script: |
            const { data: releases } = await github.repos.listReleases({ owner: context.repo.owner, repo: context.repo.repo });
            const latestRelease = releases[0];
            const version = latestRelease ? incrementVersion(latestRelease.tag_name) : '1.0.0';

            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              name: `Release ${version}`,
              draft: false,
              prerelease: false,
            });

            function incrementVersion(currentVersion) {
              const [major, minor, patch] = currentVersion.split('.').map(Number);
              return `${major}.${minor}.${patch + 1}`;
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: tag
    runs-on: ubuntu-latest

    steps:
      - name: Publish Package
        uses: actions/npm@v1
        with:
          command: "publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
